dev:
  datasource:
    url: jdbc:mysql://124.222.52.246:7945/online_judge?useSSL=false&serverTimezone=UTC
    username: root
    password: 2a002b41b9c8162f
  redis:
    database: 3
    url: redis://RedisdsbZytdsb666@124.222.52.246:3721
    timeout: 1000
