dev:
  server:
   port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge?useSSL=false&serverTimezone=UTC
    username: root
    password: wyl123...
  redis:
    database: 3
    url: redis://RedisdsbZytdsb666@124.222.52.246:3721
    timeout: 1000
  judge0:
#    SERVER_URL: http://124.222.52.246:2358/
    SERVER_URL: http://8.134.151.150:2359/
    IN_FILE_PATH: D:\CodeLife\Code\webStudy\code\Wyl_OnlineJudge\file\in\
    OUT_FILE_PATH: D:\CodeLife\Code\webStudy\code\Wyl_OnlineJudge\file\out\
  jwt:
    secret-key: jxlg-oj
    ttl: 7200000
    token-name: token